#!/bin/bash -e

cat > "${OPENSHIFT_RUBY_DIR}/lib/_override.sh" <<-'EOF'
	# Overridde!
	if [ "$_OVERRIDE" != "69" ]; then
		_OVERRIDE=69
		if [ -n "$1" ] && [ -x "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/override/$1" ]; then
			eval "function $1() { \"$OPENSHIFT_REPO_DIR/.openshift/action_hooks/override/$1\"; }"
			eval "`sed -e '/^source/d' -e "s/^[[:space:]]*function $1/ function _old_$1/" "$0"`"
			exit 0
		fi
	fi
EOF

fgrep -qx 'source "${OPENSHIFT_RUBY_DIR}/lib/_override.sh"' "${OPENSHIFT_RUBY_DIR}/lib/ruby_context" || \
	echo 'source "${OPENSHIFT_RUBY_DIR}/lib/_override.sh"' >> "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"
